name: Publish
on:
  release:
    types: [created]
  workflow_dispatch:

permissions:
  contents: write
  packages: write 
  id-token: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: 'https://npm.pkg.github.com'
          scope: '@arthurtsang'
      - run: npm ci
      - run: echo "@arthurtsang:registry=https://npm.pkg.github.com" > .npmrc
      - run: echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" >> .npmrc
      - run: ls -al
      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}


